### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by pengxiao-song** [ningkp/LfOSA#3]
Sorry to bother, another question: 
```
Traceback (most recent call last):
  File "AL_center_temperature.py", line 398, in <module>
    main()
  File "AL_center_temperature.py", line 151, in main
    trainloader_A, invalidList, use_gpu, dataset.num_classes, epoch)
  File "AL_center_temperature.py", line 259, in train_A
    loss_cent = criterion_cent(features, labels)
  File "/home/songpx/anaconda3/envs/al-osa/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/songpx/learning/al-OSA/lfosa/center_loss.py", line 38, in forward
    classes = classes.cuda()
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

Did u ever meet this problem? Actually I don't know whether this bug comes from my device..
THANKS!

**Comment by ningkp** [comment]
I haven't met it. Maybe you can print it for debugging.
